echo "Setting up ML Service..."

# Create PM2 ecosystem file
echo 'module.exports = {
  apps: [{
    name: "jobsforce-ml-service",
    script: "./venv/bin/gunicorn",
    args: "app:app --bind 0.0.0.0:5000 --workers=1",
    interpreter: "/usr/bin/python3",
    env: {
      NODE_ENV: "production",
      PYTHONUNBUFFERED: "true"
    },
    watch: false,
    max_memory_restart: "500M"
  }]
}' > ecosystem.config.js

# Start/restart the application with PM2
if pm2 list | grep -q "jobsforce-ml-service"; then
  echo "Restarting existing service..."
  pm2 restart jobsforce-ml-service
else
  echo "Starting new service..."
  pm2 start ecosystem.config.js
fi

pm2 save

echo "Setup complete!"
